name: Bug Report
description: Signaler un bug ou un probleme
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - emacsah

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug !

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug
      placeholder: Decrivez le probleme...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Etapes pour reproduire
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
      placeholder: Le comportement attendu...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il reellement ?
      placeholder: Le comportement actuel...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si applicable, ajoutez des captures d'ecran

  - type: dropdown
    id: environment
    attributes:
      label: Environnement
      options:
        - Production (folio.emacsah.com)
        - Developpement local
        - Docker
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Collez les logs pertinents ici
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Contexte additionnel
      description: Toute autre information utile
